site_name: obsidian-mkdocs template

theme:
    name: 'material'
    palette:
      # Light mode
      - media: "(prefers-color-scheme: light)"
        scheme: default
        primary: pink
        accent: indigo
        toggle:
          icon: material/toggle-switch-off-outline
          name: Switch to dark mode

      # Dark mode
      - media: "(prefers-color-scheme: dark)"
        scheme: slate
        primary: pink
        accent: blue
        toggle:
          icon: material/toggle-switch
          name: Switch to light mode

    # Footer anpassen oder entfernen
    copyright: ""  # Footer-Text (leer lassen, um ihn zu entfernen)

    # Logo und Favicon hinzufügen (optional)
    # logo: assets/logo.png
    # favicon: assets/favicon.ico

# Extensions
markdown_extensions:
  # - footnotes
  # - attr_list
  - pymdownx.arithmatex:
      generic: true
  # - pymdownx.superfences
  # - pymdownx.details
  # - pymdownx.magiclink
  - pymdownx.tasklist:
      custom_checkbox: true
  - def_list
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format

  - toc:
      permalink: true

plugins:
  - search
  - roamlinks
  - blog
  - rss:
      match_path: blog/posts/.* 
      date_from_meta:
        as_creation: date
      categories:
        - categories
        - tags

# Kategorienleiste über die Navigation hinzufügen
nav:
  - Home: index.md
  - Kategorie 1:
      - Seite 1: kategorie1/seite1.md
      - Seite 2: kategorie1/seite2.md
  - Kategorie 2:
      - Seite 3: kategorie2/seite3.md

# Benutzerdefinierte JavaScript-Dateien
extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
  - https://unpkg.com/mermaid/dist/mermaid.min.js