name: ci

on:
  push:
    branches:
      - master

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          pip install -U pip setuptools wheel
          pip install mkdocs-material mkdocs-roamlinks-plugin mkdocs-rss-plugin

      - name: Build site
        run: mkdocs build

      - name: Deploy to GitHub Pages
        run: mkdocs gh-deploy --clean --force
